url: http://YourMVP.consulting
baseurl: 

# Site settings
title: Your MVP
email: info@YourMVP.consulting
description: "Software development services for startups. We will build your MVP."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Alexey Dmitriyev
  pic: Alexey
  position: Founder
  social:
    - title: twitter
      url: http://twitter.com/admitriyev
    - title: github
      url: http://github.com/admitriyev

- name: Full Stack Developer
  pic: Alexey
  position: Founder
  social:
    - title: twitter
      url: http://twitter.com/admitriyev
    - title: github
      url: http://github.com/admitriyev

- name: UI designer
  pic: Alexey
  position: Founder
  social:
    - title: twitter
      url: http://twitter.com/admitriyev
    - title: github
      url: http://github.com/admitriyev

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/admitriyev
  - title: github
    url: http://github.com/admitriyev

# Postal address (add as many lines as necessary)
address:
  - line: Westminster, CO

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-sitemap
